STORY = "This morning %s woke up feeling %s. 'It is going to be a %s day!' Outside, a bunch of %ss were protesting to keep %s in stores. They began to %s to the rhythm of the %s, which made all the %ss very %s. Concerned, %s texted %s, who flew %s to %s and dropped %s in a puddle of frozen %s. %s woke up in the year %s, in a world where %ss ruled the world."
print ("Mad Libs has started, Enjoy!")
name = raw_input("Enter a name: ")
ad1= raw_input("Enter an adjective: ")
ad2= raw_input("Enter a second adjective: ")
ad3= raw_input("Enter one more adjective: ")
v1= raw_input ("Enter an verb: ")
n1= raw_input ("Enter an noun: ")
n2= raw_input ("Enter a second noun: ")
st1= raw_input ("Enter an animal: ")
st2= raw_input ("Enter a food: ")
st3= raw_input ("Enter a fruit: ")
st4= raw_input ("Enter a Super hero: ")
st5= raw_input ("Enter a country: ")
st6= raw_input ("Enter a dessert: ")
st7= raw_input ("Enter a year: ")
print (STORY %(name,ad1,ad2,st1,st2,v1,n1,st3,ad3,name,st4,name,st5,name,st6,name,st7,n2) )
